version: '2'

services:
  wunderlist:
    image: vturkoglu/wunderlist
    ports:
      - "8080:8080"
    depends_on:
      - couchbase

  couchbase:
    container_name: couchbase
    image: couchbase
    ports:
      - '8091:8091'
      - '8092:8092'
      - '8093:8093'
      - '8094:8094'
      - '11210:11210'
